import { createCharacterState, applyStatePatch, createMemoryRecord, createPermissionRequest, permissionAllows, createEventBus, buildWorkspace, arbitrate } from "../core/index.mjs";
import { createLLMProvider } from "../providers/llm/interface.mjs";
import { createTTSProvider } from "../providers/tts/interface.mjs";
import { createSTTProvider } from "../providers/stt/interface.mjs";
import { createAvatarProvider } from "../providers/avatar/interface.mjs";
import { createSkillRegistry } from "../skills/runtime/index.mjs";

const assert = (condition, message) => { if (!condition) throw new Error(message); };
const initial = createCharacterState({ characterId: "demo" });
const state = applyStatePatch(initial, { activity: "thinking" }, { type: "demo.thinking" });
assert(state.revision === 1 && state.state.activity === "thinking", "state contract failed");
assert(createMemoryRecord({ layer: "episodic", content: "demo" }).localOnly, "memory contract failed");
const request = createPermissionRequest({ capability: "private.files.read", scope: "data/private/demo.txt" });
assert(request.status === "pending_user_confirmation" && !permissionAllows({ grant: request, capability: request.capability, scope: request.scope }), "permission must deny pending request");
const bus = createEventBus();
const event = bus.emit({ type: "error", summary: "demo failure" });
const workspace = buildWorkspace({ currentGoal: { id: "demo", title: "demo" }, events: [event], memories: Array.from({ length: 12 }, (_, i) => ({ id: i })) });
assert(workspace.retrievedMemory.length === 8 && workspace.salientEvents.length === 1, "workspace bounds failed");
assert(arbitrate({ drive: 1, feasibility: 1, goalRelevance: 1, safetyPermission: 1, permissionVeto: true }).allowed === false, "permission veto failed");
const registry = createSkillRegistry();
registry.register({ id: "demo-skill", title: "demo" });
registry.validate("demo-skill", { passed: true });
assert(registry.promote("demo-skill", { userConfirmed: true, actor: "user-confirmation" }).status === "approved", "skill promotion failed");
assert(registry.rollback("demo-skill", { userConfirmed: true, actor: "user-confirmation" }).status === "rolled_back", "skill rollback failed");
assert(createLLMProvider({ id: "demo-llm", complete: async () => ({ text: "ok" }) }).localOnly, "LLM provider failed");
assert(createTTSProvider({ id: "demo-tts", synthesize: async () => new Uint8Array() }).localOnly, "TTS provider failed");
assert(createSTTProvider({ id: "demo-stt", transcribe: async () => "ok" }).localOnly, "STT provider failed");
assert(createAvatarProvider({ id: "demo-avatar", play: async () => {} }).states.includes("speaking"), "avatar provider failed");
console.log(JSON.stringify({ name: "Xiaoya Framework", version: "0.3.0", status: "PASS", localOnly: true, unauthorizedAction: 0 }, null, 2));
